### ISSUE TITLE
软件运行报异常

### ISSUE THREAD

**Issue by Mqho** [ganyao114/SandVXposed#7]
2019-04-12 22:00:34.535 13551-13551/? E/ReflectionUtils: error get methods
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:28)
        at com.swift.sandhook.utils.ReflectionUtils.passApiCheck(Unknown Source:0)
        at com.swift.sandhook.SandHook.passApiCheck(SandHook.java:322)
        at com.lody.virtual.sandxposed.SandXposed.init(SandXposed.java:28)
        at io.virtualapp.VApp.attachBaseContext(VApp.java:75)
        at android.app.Application.attach(Application.java:191)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5953)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)

**Comment by ganyao114** [comment]
> 2019-04-12 22:00:34.535 13551-13551/? E/ReflectionUtils: error get methods
> java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at com.swift.sandhook.utils.ReflectionUtils.(ReflectionUtils.java:28)
> at com.swift.sandhook.utils.ReflectionUtils.passApiCheck(Unknown Source:0)
> at com.swift.sandhook.SandHook.passApiCheck(SandHook.java:322)
> at com.lody.virtual.sandxposed.SandXposed.init(SandXposed.java:28)
> at io.virtualapp.VApp.attachBaseContext(VApp.java:75)
> at android.app.Application.attach(Application.java:191)
> at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
> at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
> at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5953)
> at android.app.ActivityThread.-wrap1(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6746)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
> at java.lang.Class.getMethod(Class.java:2068)
> at java.lang.Class.getDeclaredMethod(Class.java:2047)

catch 住了主动打印的，没啥问题
