### ISSUE TITLE
安卓10启动微信失败的问题

### ISSUE THREAD

**Issue by zlroy1023** [ganyao114/SandVXposed#70]
问题描述
只在sandVX安装微信，无法正常打开
必须在手机桌面上也安装一个微信，才能正常打开

复现步骤
1、下载微信，地址
https://weixin.qq.com/cgi-bin/readtemplate?uin=&stype=&promote=&fr=&lang=zh_CN&ADTAG=&check=false&t=weixin_download_method&sys=android&loc=weixin,android,web,0
2、在SandVXposed里面，手动选择路径安装微信，同时确认手机内没有安装微信
3、打开微信，显示“正在打开 微信...”后黑屏闪退至手机桌面
4、发现空指针
06-08 17:15:59.460 19419 19419 W System.err: java.lang.reflect.InvocationTargetException
06-08 17:15:59.461 19419 19419 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 17:15:59.461 19419 19419 W System.err: 	at mirror.RefStaticMethod.call(RefStaticMethod.java:119)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.env.SpecialComponentList.<clinit>(SpecialComponentList.java:78)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.env.SpecialComponentList.isConflictingInstrumentation(SpecialComponentList.java:95)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:320)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity2(HCallbackStub.java:207)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleExecuteTransaction(HCallbackStub.java:245)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:96)
06-08 17:15:59.461 19419 19419 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
06-08 17:15:59.461 19419 19419 W System.err: 	at android.os.Looper.loop(Looper.java:213)
06-08 17:15:59.461 19419 19419 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8169)
06-08 17:15:59.461 19419 19419 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 17:15:59.461 19419 19419 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-08 17:15:59.462 19419 19419 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
06-08 17:15:59.462 19419 19419 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Application.getPackageManager()' on a null object reference
06-08 17:15:59.462 19419 19419 W System.err: 	at android.webkit.WebViewFactory.isWebViewSupported(WebViewFactory.java:111)
06-08 17:15:59.462 19419 19419 W System.err: 	at android.webkit.WebViewFactory.getUpdateService(WebViewFactory.java:474)
06-08 17:15:59.462 19419 19419 W System.err: 	... 15 more

环境
机型：HUAWEI Mate 10（型号：ALP-AL00）
EMUI版本：10.0.0
Android版本：10
ROM版本：10.0.0.156（C00E156R1P4）
Xposed 插件以及插件版本：无
SandVXposed版本：1.0.0 Release
微信版本：7.0.15

**Comment by ghost** [comment]
已知问题，请添加QQ群 1013257073 下载最新版本

**Comment by tianyah** [comment]
真实桌面上不安装微信，然后选择在存储空间添加微信，在华为手机上会  java.lang.RuntimeException: Unable to create application com.tencent.mm.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
