### ISSUE TITLE
clipboard crash in Oreo

### ISSUE THREAD

**Issue by surbiks** [ganyao114/SandVXposed#74]
`2020-09-30 22:45:04.937 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(enqueueToast, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.938 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(cancelToast, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.938 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(removeAutomaticZenRules, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.939 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(areNotificationsEnabled, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.940 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(setNotificationPolicy, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.941 26926-26926/io.virtualapp.sandvxposed W/MethodInvocationStub: The Hook(isNotificationPolicyAccessGrantedForPackage, com.lody.virtual.client.hook.base.ReplaceCallingPkgMethodProxy) you added has been in existence.
2020-09-30 22:45:04.972 26926-26926/io.virtualapp.sandvxposed W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object mirror.RefObject.get(java.lang.Object)' on a null object reference
2020-09-30 22:45:04.974 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.lody.virtual.client.hook.proxies.clipboard.ClipBoardStub.getInterface(ClipBoardStub.java:29)
2020-09-30 22:45:04.974 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.lody.virtual.client.hook.proxies.clipboard.ClipBoardStub.<init>(ClipBoardStub.java:22)
2020-09-30 22:45:04.975 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.lody.virtual.client.core.InvocationStubManager.injectInternal(InvocationStubManager.java:132)
2020-09-30 22:45:04.975 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.lody.virtual.client.core.InvocationStubManager.init(InvocationStubManager.java:107)
2020-09-30 22:45:04.975 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.lody.virtual.client.core.VirtualCore.startup(VirtualCore.java:198)
2020-09-30 22:45:04.976 26926-26926/io.virtualapp.sandvxposed W/System.err:     at io.virtualapp.VApp.attachBaseContext(VApp.java:44)
2020-09-30 22:45:04.976 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.Application.attach(Application.java:213)
2020-09-30 22:45:04.976 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1109)
2020-09-30 22:45:04.977 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1093)
2020-09-30 22:45:04.977 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:973)
2020-09-30 22:45:04.977 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6036)
2020-09-30 22:45:04.977 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2020-09-30 22:45:04.978 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
2020-09-30 22:45:04.978 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
2020-09-30 22:45:04.978 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.os.Looper.loop(Looper.java:164)
2020-09-30 22:45:04.979 26926-26926/io.virtualapp.sandvxposed W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
2020-09-30 22:45:04.979 26926-26926/io.virtualapp.sandvxposed W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-09-30 22:45:04.979 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
2020-09-30 22:45:04.979 26926-26926/io.virtualapp.sandvxposed W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by ghost** [comment]
Please download and try this version: https://coolapk.com/apk/io.virtualapp.sandvxposed
Something change recently, I will tryna do something compatibility works for Android 11.
